/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7knVBmoYJW0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function Movie-Detail() {
  return (
    <div className="bg-[#0f0f0f] text-white min-h-screen">
      <header className="bg-[#1a1a1a] p-4">
        <div className="container mx-auto flex justify-between items-center">
          <div className="flex items-center space-x-4">
            <img alt="Logo" className="h-8" src="/placeholder.svg" />
            <nav className="flex space-x-4">
              <a className="text-white hover:text-gray-300" href="#">
                Phimmoi
              </a>
              <a className="text-white hover:text-gray-300" href="#">
                Phim lẻ
              </a>
              <a className="text-white hover:text-gray-300" href="#">
                Phim bộ
              </a>
              <a className="text-white hover:text-gray-300" href="#">
                Thể loại
              </a>
              <a className="text-white hover:text-gray-300" href="#">
                Quốc gia
              </a>
              <a className="text-white hover:text-gray-300" href="#">
                Phim mới
              </a>
            </nav>
          </div>
          <div className="flex items-center space-x-4">
            <input className="text-black p-2" placeholder="Tìm kiếm..." type="text" />
            <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Tìm kiếm</button>
          </div>
        </div>
      </header>
      <main className="container mx-auto p-4">
        <div className="grid grid-cols-4 gap-4">
          <div className="col-span-3">
            <div className="space-y-4">
              <div className="aspect-w-16 aspect-h-9 bg-gray-800" />
              <div className="flex justify-between items-center">
                <h1 className="text-xl font-bold">Tên phim</h1>
                <button className="text-sm bg-red-600 hover:bg-red-800 text-white font-bold py-1 px-2 rounded">
                  Report Error
                </button>
              </div>
              <div>
                <p className="text-gray-400">Chọn server</p>
                <div className="flex space-x-2">
                  <button className="bg-gray-700 hover:bg-gray-600 text-white font-bold py-1 px-2 rounded">
                    YouTube 1
                  </button>
                  <button className="bg-gray-700 hover:bg-gray-600 text-white font-bold py-1 px-2 rounded">
                    YouTube 2
                  </button>
                </div>
              </div>
              <div>
                <p className="text-gray-400">Nội dung</p>
                <p className="text-sm text-gray-300">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et
                  dolore magna aliqua.
                </p>
              </div>
              <div className="flex justify-between items-center">
                <button className="bg-gray-700 hover:bg-gray-600 text-white font-bold py-1 px-2 rounded">Prev</button>
                <button className="bg-gray-700 hover:bg-gray-600 text-white font-bold py-1 px-2 rounded">Next</button>
              </div>
            </div>
          </div>
          <div className="col-span-1">
            <div className="space-y-4">
              <div className="space-y-2">
                <h2 className="text-lg font-bold">Năm phát hành</h2>
                <div className="flex flex-col space-y-1">
                  <a className="text-gray-400 hover:text-white" href="#">
                    2023
                  </a>
                  <a className="text-gray-400 hover:text-white" href="#">
                    2022
                  </a>
                  <a className="text-gray-400 hover:text-white" href="#">
                    2021
                  </a>
                  <a className="text-gray-400 hover:text-white" href="#">
                    2020
                  </a>
                  <a className="text-gray-400 hover:text-white" href="#">
                    2019
                  </a>
                </div>
              </div>
              <div className="space-y-2">
                <h2 className="text-lg font-bold">Các diễn viên</h2>
                <div className="flex flex-col space-y-1">
                  <a className="text-gray-400 hover:text-white" href="#">
                    Diễn viên A
                  </a>
                  <a className="text-gray-400 hover:text-white" href="#">
                    Diễn viên B
                  </a>
                  <a className="text-gray-400 hover:text-white" href="#">
                    Diễn viên C
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className="bg-[#1a1a1a] p-4 mt-4">
        <div className="container mx-auto text-center text-sm text-gray-400">© 2023 Phimmoi.net</div>
      </footer>
    </div>
  )
}
